-- PostgreSQL Schema Migration: 004_tables.sql
-- Description: Table definitions for all 118 legacy tables

-- Table: tblactivity_log
CREATE TABLE IF NOT EXISTS tblactivity_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    description TEXT NOT NULL,
    date TIMESTAMP NOT NULL,
    staffid VARCHAR(100)
);

-- Table: tblannouncements
CREATE TABLE IF NOT EXISTS tblannouncements (
    announcementid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(191) NOT NULL,
    message TEXT,
    showtousers INTEGER NOT NULL,
    showtostaff INTEGER NOT NULL,
    showname INTEGER NOT NULL,
    dateadded TIMESTAMP NOT NULL,
    userid VARCHAR(100) NOT NULL
);

-- Table: tblclients
CREATE TABLE IF NOT EXISTS tblclients (
    userid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    company VARCHAR(191),
    vat VARCHAR(50),
    phonenumber VARCHAR(30),
    country INTEGER NOT NULL DEFAULT 0,
    city VARCHAR(100),
    zip VARCHAR(15),
    state VARCHAR(50),
    address VARCHAR(191),
    website VARCHAR(150),
    datecreated TIMESTAMP NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    leadid INTEGER,
    billing_street VARCHAR(200),
    billing_city VARCHAR(100),
    billing_state VARCHAR(100),
    billing_zip VARCHAR(100),
    billing_country INTEGER DEFAULT 0,
    shipping_street VARCHAR(200),
    shipping_city VARCHAR(100),
    shipping_state VARCHAR(100),
    shipping_zip VARCHAR(100),
    shipping_country INTEGER DEFAULT 0,
    longitude VARCHAR(191),
    latitude VARCHAR(191),
    default_language VARCHAR(40),
    default_currency INTEGER NOT NULL DEFAULT 0,
    show_primary_contact INTEGER NOT NULL DEFAULT 0,
    stripe_id VARCHAR(40),
    registration_confirmed INTEGER NOT NULL DEFAULT 1,
    addedfrom INTEGER NOT NULL DEFAULT 0
);

-- Table: tblconsents
CREATE TABLE IF NOT EXISTS tblconsents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    action VARCHAR(10) NOT NULL,
    date TIMESTAMP NOT NULL,
    ip VARCHAR(40) NOT NULL,
    contact_id INTEGER NOT NULL DEFAULT 0,
    lead_id INTEGER NOT NULL DEFAULT 0,
    description TEXT,
    opt_in_purpose_description TEXT,
    purpose_id INTEGER NOT NULL,
    staff_name VARCHAR(100)
);

-- Table: tblconsent_purposes
CREATE TABLE IF NOT EXISTS tblconsent_purposes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    date_created TIMESTAMP NOT NULL,
    last_updated TIMESTAMP
);

-- Table: tblcontacts
CREATE TABLE IF NOT EXISTS tblcontacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    userid INTEGER NOT NULL,
    is_primary INTEGER NOT NULL DEFAULT 1,
    firstname VARCHAR(191) NOT NULL,
    lastname VARCHAR(191) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phonenumber VARCHAR(100) NOT NULL,
    title VARCHAR(100),
    datecreated TIMESTAMP NOT NULL,
    password VARCHAR(255),
    new_pass_key VARCHAR(32),
    new_pass_key_requested TIMESTAMP,
    email_verified_at TIMESTAMP,
    email_verification_key VARCHAR(32),
    email_verification_sent_at TIMESTAMP,
    last_ip VARCHAR(40),
    last_login TIMESTAMP,
    last_password_change TIMESTAMP,
    active SMALLINT NOT NULL DEFAULT 1,
    profile_image VARCHAR(191),
    direction VARCHAR(3),
    invoice_emails SMALLINT NOT NULL DEFAULT 1,
    estimate_emails SMALLINT NOT NULL DEFAULT 1,
    credit_note_emails SMALLINT NOT NULL DEFAULT 1,
    contract_emails SMALLINT NOT NULL DEFAULT 1,
    task_emails SMALLINT NOT NULL DEFAULT 1,
    project_emails SMALLINT NOT NULL DEFAULT 1,
    ticket_emails SMALLINT NOT NULL DEFAULT 1
);

-- Table: tblcontact_permissions
CREATE TABLE IF NOT EXISTS tblcontact_permissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    permission_id INTEGER NOT NULL,
    userid INTEGER NOT NULL
);

-- Table: tblcontracts
CREATE TABLE IF NOT EXISTS tblcontracts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    content TEXT,
    description TEXT,
    subject VARCHAR(191),
    client INTEGER NOT NULL,
    datestart DATE,
    dateend DATE,
    contract_type INTEGER,
    project_id INTEGER,
    addedfrom INTEGER NOT NULL,
    dateadded TIMESTAMP NOT NULL,
    isexpirynotified INTEGER NOT NULL DEFAULT 0,
    contract_value NUMERIC(15,2),
    trash SMALLINT DEFAULT 0,
    not_visible_to_client SMALLINT NOT NULL DEFAULT 0,
    hash VARCHAR(32),
    signed SMALLINT NOT NULL DEFAULT 0,
    signature VARCHAR(40),
    marked_as_signed SMALLINT NOT NULL DEFAULT 0,
    acceptance_firstname VARCHAR(50),
    acceptance_lastname VARCHAR(50),
    acceptance_email VARCHAR(100),
    acceptance_date TIMESTAMP,
    acceptance_ip VARCHAR(40),
    short_link VARCHAR(100),
    last_sent_at TIMESTAMP,
    contacts_sent_to TEXT,
    last_sign_reminder_at TIMESTAMP
);

-- Table: tblcontracts_types
CREATE TABLE IF NOT EXISTS tblcontracts_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);

-- Table: tblcontract_comments
CREATE TABLE IF NOT EXISTS tblcontract_comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    content TEXT,
    contract_id INTEGER NOT NULL,
    staffid INTEGER NOT NULL,
    dateadded TIMESTAMP NOT NULL
);

-- Table: tblcontract_renewals
CREATE TABLE IF NOT EXISTS tblcontract_renewals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    contractid INTEGER NOT NULL,
    old_start_date DATE NOT NULL,
    new_start_date DATE NOT NULL,
    old_end_date DATE,
    new_end_date DATE,
    old_value NUMERIC(15,2),
    new_value NUMERIC(15,2),
    date_renewed TIMESTAMP NOT NULL,
    renewed_by VARCHAR(100) NOT NULL,
    renewed_by_staff_id INTEGER NOT NULL DEFAULT 0,
    is_on_old_expiry_notified INTEGER DEFAULT 0
);

-- Table: tblcountries
CREATE TABLE IF NOT EXISTS tblcountries (
    country_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    iso2 CHAR(2),
    short_name VARCHAR(80) NOT NULL DEFAULT '',
    long_name VARCHAR(80) NOT NULL DEFAULT '',
    iso3 CHAR(3),
    numcode VARCHAR(6),
    un_member VARCHAR(12),
    calling_code VARCHAR(8),
    cctld VARCHAR(5)
);

-- Table: tblcreditnotes
CREATE TABLE IF NOT EXISTS tblcreditnotes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    clientid INTEGER NOT NULL,
    deleted_customer_name VARCHAR(100),
    number INTEGER NOT NULL,
    prefix VARCHAR(50),
    number_format INTEGER NOT NULL DEFAULT 1,
    formatted_number VARCHAR(100),
    datecreated TIMESTAMP NOT NULL,
    date DATE NOT NULL,
    adminnote TEXT,
    terms TEXT,
    clientnote TEXT,
    currency INTEGER NOT NULL,
    subtotal NUMERIC(15,2) NOT NULL,
    total_tax NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    total NUMERIC(15,2) NOT NULL,
    adjustment NUMERIC(15,2),
    addedfrom INTEGER,
    status INTEGER DEFAULT 1,
    project_id INTEGER NOT NULL DEFAULT 0,
    discount_percent NUMERIC(15,2) DEFAULT 0.00,
    discount_total NUMERIC(15,2) DEFAULT 0.00,
    discount_type VARCHAR(30) NOT NULL,
    billing_street VARCHAR(200),
    billing_city VARCHAR(100),
    billing_state VARCHAR(100),
    billing_zip VARCHAR(100),
    billing_country INTEGER,
    shipping_street VARCHAR(200),
    shipping_city VARCHAR(100),
    shipping_state VARCHAR(100),
    shipping_zip VARCHAR(100),
    shipping_country INTEGER,
    include_shipping SMALLINT NOT NULL,
    show_shipping_on_credit_note SMALLINT NOT NULL DEFAULT 1,
    show_quantity_as INTEGER NOT NULL DEFAULT 1,
    reference_no VARCHAR(100)
);

-- Table: tblcreditnote_refunds
CREATE TABLE IF NOT EXISTS tblcreditnote_refunds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    credit_note_id INTEGER NOT NULL,
    staff_id INTEGER NOT NULL,
    refunded_on DATE NOT NULL,
    payment_mode VARCHAR(40) NOT NULL,
    note TEXT,
    amount NUMERIC(15,2) NOT NULL,
    created_at TIMESTAMP
);

-- Table: tblcredits
CREATE TABLE IF NOT EXISTS tblcredits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    invoice_id INTEGER NOT NULL,
    credit_id INTEGER NOT NULL,
    staff_id INTEGER NOT NULL,
    date DATE NOT NULL,
    date_applied TIMESTAMP NOT NULL,
    amount NUMERIC(15,2) NOT NULL
);

-- Table: tblcurrencies
CREATE TABLE IF NOT EXISTS tblcurrencies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    decimal_separator VARCHAR(5),
    thousand_separator VARCHAR(5),
    placement VARCHAR(10),
    isdefault SMALLINT NOT NULL DEFAULT 0
);

-- Table: tblcustomers_groups
CREATE TABLE IF NOT EXISTS tblcustomers_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(191) NOT NULL
);

-- Table: tblcustomer_admins
CREATE TABLE IF NOT EXISTS tblcustomer_admins (
    staff_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    date_assigned TEXT NOT NULL
);

-- Table: tblcustomer_groups
CREATE TABLE IF NOT EXISTS tblcustomer_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    groupid INTEGER NOT NULL,
    customer_id INTEGER NOT NULL
);

-- Table: tblcustomfields
CREATE TABLE IF NOT EXISTS tblcustomfields (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    fieldto VARCHAR(30),
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(150) NOT NULL,
    required SMALLINT NOT NULL DEFAULT 0,
    type VARCHAR(20) NOT NULL,
    options TEXT,
    display_inline SMALLINT NOT NULL DEFAULT 0,
    field_order INTEGER DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    show_on_pdf INTEGER NOT NULL DEFAULT 0,
    show_on_ticket_form SMALLINT NOT NULL DEFAULT 0,
    only_admin SMALLINT NOT NULL DEFAULT 0,
    show_on_table SMALLINT NOT NULL DEFAULT 0,
    show_on_client_portal INTEGER NOT NULL DEFAULT 0,
    disalow_client_to_edit INTEGER NOT NULL DEFAULT 0,
    bs_column INTEGER NOT NULL DEFAULT 12,
    default_value TEXT
);

-- Table: tblcustomfieldsvalues
CREATE TABLE IF NOT EXISTS tblcustomfieldsvalues (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    relid INTEGER NOT NULL,
    fieldid INTEGER NOT NULL,
    fieldto VARCHAR(15) NOT NULL,
    value TEXT NOT NULL
);

-- Table: tbldepartments
CREATE TABLE IF NOT EXISTS tbldepartments (
    departmentid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    imap_username VARCHAR(191),
    email VARCHAR(100),
    email_from_header SMALLINT NOT NULL DEFAULT 0,
    host VARCHAR(150),
    password TEXT,
    encryption VARCHAR(3),
    folder VARCHAR(191) NOT NULL DEFAULT 'INBOX',
    delete_after_import INTEGER NOT NULL DEFAULT 0,
    calendar_id TEXT,
    hidefromclient SMALLINT NOT NULL DEFAULT 0
);

-- Table: tbldismissed_announcements
CREATE TABLE IF NOT EXISTS tbldismissed_announcements (
    dismissedannouncementid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    announcementid INTEGER NOT NULL,
    staff INTEGER NOT NULL,
    userid INTEGER NOT NULL
);

-- Table: tblemailtemplates
CREATE TABLE IF NOT EXISTS tblemailtemplates (
    emailtemplateid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    type TEXT NOT NULL,
    slug VARCHAR(100) NOT NULL,
    language VARCHAR(40),
    name TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    fromname TEXT NOT NULL,
    fromemail VARCHAR(100),
    plaintext INTEGER NOT NULL DEFAULT 0,
    active SMALLINT NOT NULL DEFAULT 0,
    order INTEGER NOT NULL
);

-- Table: tblestimates
CREATE TABLE IF NOT EXISTS tblestimates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    sent SMALLINT NOT NULL DEFAULT 0,
    datesend TIMESTAMP,
    clientid INTEGER NOT NULL,
    deleted_customer_name VARCHAR(100),
    project_id INTEGER NOT NULL DEFAULT 0,
    number INTEGER NOT NULL,
    prefix VARCHAR(50),
    number_format INTEGER NOT NULL DEFAULT 0,
    formatted_number VARCHAR(100),
    hash VARCHAR(32),
    datecreated TIMESTAMP NOT NULL,
    date DATE NOT NULL,
    expirydate DATE,
    currency INTEGER NOT NULL,
    subtotal NUMERIC(15,2) NOT NULL,
    total_tax NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    total NUMERIC(15,2) NOT NULL,
    adjustment NUMERIC(15,2),
    addedfrom INTEGER NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    clientnote TEXT,
    adminnote TEXT,
    discount_percent NUMERIC(15,2) DEFAULT 0.00,
    discount_total NUMERIC(15,2) DEFAULT 0.00,
    discount_type VARCHAR(30),
    invoiceid INTEGER,
    invoiced_date TIMESTAMP,
    terms TEXT,
    reference_no VARCHAR(100),
    sale_agent INTEGER NOT NULL DEFAULT 0,
    billing_street VARCHAR(200),
    billing_city VARCHAR(100),
    billing_state VARCHAR(100),
    billing_zip VARCHAR(100),
    billing_country INTEGER,
    shipping_street VARCHAR(200),
    shipping_city VARCHAR(100),
    shipping_state VARCHAR(100),
    shipping_zip VARCHAR(100),
    shipping_country INTEGER,
    include_shipping SMALLINT NOT NULL,
    show_shipping_on_estimate SMALLINT NOT NULL DEFAULT 1,
    show_quantity_as INTEGER NOT NULL DEFAULT 1,
    pipeline_order INTEGER DEFAULT 1,
    is_expiry_notified INTEGER NOT NULL DEFAULT 0,
    acceptance_firstname VARCHAR(50),
    acceptance_lastname VARCHAR(50),
    acceptance_email VARCHAR(100),
    acceptance_date TIMESTAMP,
    acceptance_ip VARCHAR(40),
    signature VARCHAR(40),
    short_link VARCHAR(100)
);

-- Table: tblestimate_requests
CREATE TABLE IF NOT EXISTS tblestimate_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(100) NOT NULL,
    submission TEXT NOT NULL,
    last_status_change TIMESTAMP,
    date_estimated TIMESTAMP,
    from_form_id INTEGER,
    assigned INTEGER,
    status INTEGER,
    default_language INTEGER NOT NULL,
    date_added TIMESTAMP NOT NULL
);

-- Table: tblestimate_request_forms
CREATE TABLE IF NOT EXISTS tblestimate_request_forms (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    form_key VARCHAR(32) NOT NULL,
    type VARCHAR(100) NOT NULL,
    name VARCHAR(191) NOT NULL,
    form_data TEXT,
    recaptcha INTEGER,
    status INTEGER NOT NULL,
    submit_btn_name VARCHAR(100),
    submit_btn_bg_color VARCHAR(10) DEFAULT '#84c529',
    submit_btn_text_color VARCHAR(10) DEFAULT '#ffffff',
    success_submit_msg TEXT,
    submit_action INTEGER DEFAULT 0,
    submit_redirect_url TEXT,
    language VARCHAR(100),
    dateadded TIMESTAMP,
    notify_type VARCHAR(100),
    notify_ids TEXT,
    responsible INTEGER,
    notify_request_submitted INTEGER NOT NULL DEFAULT 0
);

-- Table: tblestimate_request_status
CREATE TABLE IF NOT EXISTS tblestimate_request_status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    statusorder INTEGER,
    color VARCHAR(10),
    flag VARCHAR(30)
);

-- Table: tblevents
CREATE TABLE IF NOT EXISTS tblevents (
    eventid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    userid INTEGER NOT NULL,
    start TIMESTAMP NOT NULL,
    end TIMESTAMP,
    public INTEGER NOT NULL DEFAULT 0,
    color VARCHAR(10),
    isstartnotified SMALLINT NOT NULL DEFAULT 0,
    reminder_before INTEGER NOT NULL DEFAULT 0,
    reminder_before_type VARCHAR(10)
);

-- Table: tblexpenses
CREATE TABLE IF NOT EXISTS tblexpenses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    category INTEGER NOT NULL,
    currency INTEGER NOT NULL,
    amount NUMERIC(15,2) NOT NULL,
    tax INTEGER,
    tax2 INTEGER NOT NULL DEFAULT 0,
    reference_no VARCHAR(100),
    note TEXT,
    expense_name VARCHAR(191),
    clientid INTEGER NOT NULL,
    project_id INTEGER NOT NULL DEFAULT 0,
    billable INTEGER DEFAULT 0,
    invoiceid INTEGER,
    paymentmode VARCHAR(50),
    date DATE NOT NULL,
    recurring_type VARCHAR(10),
    repeat_every INTEGER,
    recurring INTEGER NOT NULL DEFAULT 0,
    cycles INTEGER NOT NULL DEFAULT 0,
    total_cycles INTEGER NOT NULL DEFAULT 0,
    custom_recurring INTEGER NOT NULL DEFAULT 0,
    last_recurring_date DATE,
    create_invoice_billable SMALLINT,
    send_invoice_to_customer SMALLINT NOT NULL,
    recurring_from INTEGER,
    dateadded TIMESTAMP NOT NULL,
    addedfrom INTEGER NOT NULL
);

-- Table: tblexpenses_categories
CREATE TABLE IF NOT EXISTS tblexpenses_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(191) NOT NULL,
    description TEXT
);

-- Table: tblfiles
CREATE TABLE IF NOT EXISTS tblfiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    rel_id INTEGER NOT NULL,
    rel_type VARCHAR(20) NOT NULL,
    file_name VARCHAR(191) NOT NULL,
    filetype VARCHAR(40),
    visible_to_customer INTEGER NOT NULL DEFAULT 0,
    attachment_key VARCHAR(32),
    external VARCHAR(40),
    external_link TEXT,
    thumbnail_link TEXT,
    staffid INTEGER NOT NULL,
    contact_id INTEGER DEFAULT 0,
    task_comment_id INTEGER NOT NULL DEFAULT 0,
    dateadded TIMESTAMP NOT NULL
);

-- Table: tblfilters
CREATE TABLE IF NOT EXISTS tblfilters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(191) NOT NULL,
    builder TEXT NOT NULL,
    staff_id INTEGER NOT NULL,
    identifier VARCHAR(191) NOT NULL,
    is_shared SMALLINT NOT NULL DEFAULT 0
);

-- Table: tblfilter_defaults
CREATE TABLE IF NOT EXISTS tblfilter_defaults (
    filter_id INTEGER NOT NULL,
    staff_id INTEGER NOT NULL,
    identifier VARCHAR(191) NOT NULL,
    view VARCHAR(191) NOT NULL
);

-- Table: tblform_questions
CREATE TABLE IF NOT EXISTS tblform_questions (
    questionid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    rel_id INTEGER NOT NULL,
    rel_type VARCHAR(20),
    question TEXT NOT NULL,
    required SMALLINT NOT NULL DEFAULT 0,
    question_order INTEGER NOT NULL
);

-- Table: tblform_question_box
CREATE TABLE IF NOT EXISTS tblform_question_box (
    boxid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    boxtype VARCHAR(10) NOT NULL,
    questionid INTEGER NOT NULL
);

-- Table: tblform_question_box_description
CREATE TABLE IF NOT EXISTS tblform_question_box_description (
    questionboxdescriptionid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    description TEXT NOT NULL,
    boxid TEXT NOT NULL,
    questionid INTEGER NOT NULL
);

-- Table: tblform_results
CREATE TABLE IF NOT EXISTS tblform_results (
    resultid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    boxid INTEGER NOT NULL,
    boxdescriptionid INTEGER,
    rel_id INTEGER NOT NULL,
    rel_type VARCHAR(20),
    questionid INTEGER NOT NULL,
    answer TEXT,
    resultsetid INTEGER NOT NULL
);

-- Table: tblgdpr_requests
CREATE TABLE IF NOT EXISTS tblgdpr_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    clientid INTEGER NOT NULL DEFAULT 0,
    contact_id INTEGER NOT NULL DEFAULT 0,
    lead_id INTEGER NOT NULL DEFAULT 0,
    request_type VARCHAR(191),
    status VARCHAR(40),
    request_date TIMESTAMP NOT NULL,
    request_from VARCHAR(150),
    description TEXT
);

-- Table: tblinvoicepaymentrecords
CREATE TABLE IF NOT EXISTS tblinvoicepaymentrecords (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    invoiceid INTEGER NOT NULL,
    amount NUMERIC(15,2) NOT NULL,
    paymentmode VARCHAR(40),
    paymentmethod VARCHAR(191),
    date DATE NOT NULL,
    daterecorded TIMESTAMP NOT NULL,
    note TEXT,
    transactionid TEXT
);

-- Table: tblinvoices
CREATE TABLE IF NOT EXISTS tblinvoices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    sent SMALLINT NOT NULL DEFAULT 0,
    datesend TIMESTAMP,
    clientid INTEGER NOT NULL,
    deleted_customer_name VARCHAR(100),
    number INTEGER NOT NULL,
    prefix VARCHAR(50),
    number_format INTEGER NOT NULL DEFAULT 0,
    formatted_number VARCHAR(100),
    datecreated TIMESTAMP NOT NULL,
    date DATE NOT NULL,
    duedate DATE,
    currency INTEGER NOT NULL,
    subtotal NUMERIC(15,2) NOT NULL,
    total_tax NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    total NUMERIC(15,2) NOT NULL,
    adjustment NUMERIC(15,2),
    addedfrom INTEGER,
    hash VARCHAR(32) NOT NULL,
    status INTEGER DEFAULT 1,
    clientnote TEXT,
    adminnote TEXT,
    last_overdue_reminder DATE,
    last_due_reminder DATE,
    cancel_overdue_reminders INTEGER NOT NULL DEFAULT 0,
    allowed_payment_modes TEXT,
    token TEXT,
    discount_percent NUMERIC(15,2) DEFAULT 0.00,
    discount_total NUMERIC(15,2) DEFAULT 0.00,
    discount_type VARCHAR(30) NOT NULL,
    recurring INTEGER NOT NULL DEFAULT 0,
    recurring_type VARCHAR(10),
    custom_recurring SMALLINT NOT NULL DEFAULT 0,
    cycles INTEGER NOT NULL DEFAULT 0,
    total_cycles INTEGER NOT NULL DEFAULT 0,
    is_recurring_from INTEGER,
    last_recurring_date DATE,
    terms TEXT,
    sale_agent INTEGER NOT NULL DEFAULT 0,
    billing_street VARCHAR(200),
    billing_city VARCHAR(100),
    billing_state VARCHAR(100),
    billing_zip VARCHAR(100),
    billing_country INTEGER,
    shipping_street VARCHAR(200),
    shipping_city VARCHAR(100),
    shipping_state VARCHAR(100),
    shipping_zip VARCHAR(100),
    shipping_country INTEGER,
    include_shipping SMALLINT NOT NULL,
    show_shipping_on_invoice SMALLINT NOT NULL DEFAULT 1,
    show_quantity_as INTEGER NOT NULL DEFAULT 1,
    project_id INTEGER DEFAULT 0,
    subscription_id INTEGER NOT NULL DEFAULT 0,
    short_link VARCHAR(100)
);

-- Table: tblitemable
CREATE TABLE IF NOT EXISTS tblitemable (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    rel_id INTEGER NOT NULL,
    rel_type VARCHAR(15) NOT NULL,
    description TEXT NOT NULL,
    long_description TEXT,
    qty NUMERIC(15,2) NOT NULL,
    rate NUMERIC(15,2) NOT NULL,
    unit VARCHAR(40),
    is_optional SMALLINT NOT NULL DEFAULT 0,
    is_selected SMALLINT NOT NULL DEFAULT 1,
    item_order INTEGER
);

-- Table: tblitems
CREATE TABLE IF NOT EXISTS tblitems (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    description TEXT NOT NULL,
    long_description TEXT,
    rate NUMERIC(15,2) NOT NULL,
    tax INTEGER,
    tax2 INTEGER,
    unit VARCHAR(40),
    group_id INTEGER NOT NULL DEFAULT 0
);

-- Table: tblitems_groups
CREATE TABLE IF NOT EXISTS tblitems_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL
);

-- Table: tblitem_tax
CREATE TABLE IF NOT EXISTS tblitem_tax (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    itemid INTEGER NOT NULL,
    rel_id INTEGER NOT NULL,
    rel_type VARCHAR(20) NOT NULL,
    taxrate NUMERIC(15,2) NOT NULL,
    taxname VARCHAR(100) NOT NULL
);

-- Table: tblknowedge_base_article_feedback
CREATE TABLE IF NOT EXISTS tblknowedge_base_article_feedback (
    articleanswerid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    articleid INTEGER NOT NULL,
    answer INTEGER NOT NULL,
    ip VARCHAR(40) NOT NULL,
    date TIMESTAMP NOT NULL
);

-- Table: tblknowledge_base
CREATE TABLE IF NOT EXISTS tblknowledge_base (
    articleid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    articlegroup INTEGER NOT NULL,
    subject TEXT NOT NULL,
    description TEXT NOT NULL,
    slug TEXT NOT NULL,
    active SMALLINT NOT NULL,
    datecreated TIMESTAMP NOT NULL,
    article_order INTEGER NOT NULL DEFAULT 0,
    staff_article INTEGER NOT NULL DEFAULT 0
);

-- Table: tblknowledge_base_groups
CREATE TABLE IF NOT EXISTS tblknowledge_base_groups (
    groupid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(191) NOT NULL,
    group_slug TEXT,
    description TEXT,
    active SMALLINT NOT NULL,
    color VARCHAR(10) DEFAULT '#28B8DA',
    group_order INTEGER DEFAULT 0
);

-- Table: tblleads
CREATE TABLE IF NOT EXISTS tblleads (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    hash VARCHAR(65),
    name VARCHAR(191) NOT NULL,
    title VARCHAR(100),
    company VARCHAR(191),
    description TEXT,
    country INTEGER NOT NULL DEFAULT 0,
    zip VARCHAR(15),
    city VARCHAR(100),
    state VARCHAR(50),
    address VARCHAR(100),
    assigned INTEGER NOT NULL DEFAULT 0,
    dateadded TIMESTAMP NOT NULL,
    from_form_id INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL,
    source INTEGER NOT NULL,
    lastcontact TIMESTAMP,
    dateassigned DATE,
    last_status_change TIMESTAMP,
    addedfrom INTEGER NOT NULL,
    email VARCHAR(100),
    website VARCHAR(150),
    leadorder INTEGER DEFAULT 1,
    phonenumber VARCHAR(50),
    date_converted TIMESTAMP,
    lost SMALLINT NOT NULL DEFAULT 0,
    junk INTEGER NOT NULL DEFAULT 0,
    last_lead_status INTEGER NOT NULL DEFAULT 0,
    is_imported_from_email_integration SMALLINT NOT NULL DEFAULT 0,
    email_integration_uid VARCHAR(30),
    is_public SMALLINT NOT NULL DEFAULT 0,
    default_language VARCHAR(40),
    client_id INTEGER NOT NULL DEFAULT 0,
    lead_value NUMERIC(15,2)
);

-- Table: tblleads_email_integration
CREATE TABLE IF NOT EXISTS tblleads_email_integration (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    active INTEGER NOT NULL,
    email VARCHAR(100) NOT NULL,
    imap_server VARCHAR(100) NOT NULL,
    password TEXT NOT NULL,
    check_every INTEGER NOT NULL DEFAULT 5,
    responsible INTEGER NOT NULL,
    lead_source INTEGER NOT NULL,
    lead_status INTEGER NOT NULL,
    encryption VARCHAR(3),
    folder VARCHAR(100) NOT NULL,
    last_run VARCHAR(50),
    notify_lead_imported SMALLINT NOT NULL DEFAULT 1,
    notify_lead_contact_more_times SMALLINT NOT NULL DEFAULT 1,
    notify_type VARCHAR(20),
    notify_ids TEXT,
    mark_public INTEGER NOT NULL DEFAULT 0,
    only_loop_on_unseen_emails SMALLINT NOT NULL DEFAULT 1,
    delete_after_import INTEGER NOT NULL DEFAULT 0,
    create_task_if_customer INTEGER NOT NULL DEFAULT 0
);

-- Table: tblleads_sources
CREATE TABLE IF NOT EXISTS tblleads_sources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL
);

-- Table: tblleads_status
CREATE TABLE IF NOT EXISTS tblleads_status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    statusorder INTEGER,
    color VARCHAR(10) DEFAULT '#28B8DA',
    isdefault INTEGER NOT NULL DEFAULT 0
);

-- Table: tbllead_activity_log
CREATE TABLE IF NOT EXISTS tbllead_activity_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    leadid INTEGER NOT NULL,
    description TEXT NOT NULL,
    additional_data TEXT,
    date TIMESTAMP NOT NULL,
    staffid INTEGER NOT NULL,
    full_name VARCHAR(100),
    custom_activity SMALLINT NOT NULL DEFAULT 0
);

-- Table: tbllead_integration_emails
CREATE TABLE IF NOT EXISTS tbllead_integration_emails (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    subject TEXT,
    body TEXT,
    dateadded TIMESTAMP NOT NULL,
    leadid INTEGER NOT NULL,
    emailid INTEGER NOT NULL
);

-- Table: tblmail_queue
CREATE TABLE IF NOT EXISTS tblmail_queue (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    engine VARCHAR(40),
    email VARCHAR(191) NOT NULL,
    cc TEXT,
    bcc TEXT,
    message TEXT NOT NULL,
    alt_message TEXT,
    status VARCHAR,
    date TIMESTAMP,
    headers TEXT,
    attachments TEXT
);

-- Table: tblmigrations
CREATE TABLE IF NOT EXISTS tblmigrations (
    version BIGINT NOT NULL
);

-- Table: tblmilestones
CREATE TABLE IF NOT EXISTS tblmilestones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(191) NOT NULL,
    description TEXT,
    description_visible_to_customer SMALLINT DEFAULT 0,
    start_date DATE,
    due_date DATE NOT NULL,
    project_id INTEGER NOT NULL,
    color VARCHAR(10),
    milestone_order INTEGER NOT NULL DEFAULT 0,
    datecreated DATE NOT NULL,
    hide_from_customer INTEGER DEFAULT 0
);

-- Table: tblmodules
CREATE TABLE IF NOT EXISTS tblmodules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    module_name VARCHAR(55) NOT NULL,
    installed_version VARCHAR(11) NOT NULL,
    active SMALLINT NOT NULL
);

-- Table: tblnewsfeed_comment_likes
CREATE TABLE IF NOT EXISTS tblnewsfeed_comment_likes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    postid INTEGER NOT NULL,
    commentid INTEGER NOT NULL,
    userid INTEGER NOT NULL,
    dateliked TIMESTAMP NOT NULL
);

-- Table: tblnewsfeed_posts
CREATE TABLE IF NOT EXISTS tblnewsfeed_posts (
    postid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    creator INTEGER NOT NULL,
    datecreated TIMESTAMP NOT NULL,
    visibility VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    pinned INTEGER NOT NULL,
    datepinned TIMESTAMP
);

-- Table: tblnewsfeed_post_comments
CREATE TABLE IF NOT EXISTS tblnewsfeed_post_comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    content TEXT,
    userid INTEGER NOT NULL,
    postid INTEGER NOT NULL,
    dateadded TIMESTAMP NOT NULL
);

-- Table: tblnewsfeed_post_likes
CREATE TABLE IF NOT EXISTS tblnewsfeed_post_likes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    postid INTEGER NOT NULL,
    userid INTEGER NOT NULL,
    dateliked TIMESTAMP NOT NULL
);

-- Table: tblnotes
CREATE TABLE IF NOT EXISTS tblnotes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    rel_id INTEGER NOT NULL,
    rel_type VARCHAR(20) NOT NULL,
    description TEXT,
    date_contacted TIMESTAMP,
    addedfrom INTEGER NOT NULL,
    dateadded TIMESTAMP NOT NULL
);

-- Table: tblnotifications
CREATE TABLE IF NOT EXISTS tblnotifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    isread INTEGER NOT NULL DEFAULT 0,
    isread_inline SMALLINT NOT NULL DEFAULT 0,
    date TIMESTAMP NOT NULL,
    description TEXT NOT NULL,
    fromuserid INTEGER NOT NULL,
    fromclientid INTEGER NOT NULL DEFAULT 0,
    from_fullname VARCHAR(100) NOT NULL,
    touserid INTEGER NOT NULL,
    fromcompany INTEGER,
    link TEXT,
    additional_data TEXT
);

-- Table: tbloptions
CREATE TABLE IF NOT EXISTS tbloptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(191) NOT NULL,
    value TEXT NOT NULL,
    autoload SMALLINT NOT NULL DEFAULT 1
);

-- Table: tblpayment_attempts
CREATE TABLE IF NOT EXISTS tblpayment_attempts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    reference VARCHAR(100) NOT NULL,
    invoice_id INTEGER NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    fee DOUBLE PRECISION NOT NULL,
    payment_gateway VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- Table: tblpayment_modes
CREATE TABLE IF NOT EXISTS tblpayment_modes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    show_on_pdf INTEGER NOT NULL DEFAULT 0,
    invoices_only INTEGER NOT NULL DEFAULT 0,
    expenses_only INTEGER NOT NULL DEFAULT 0,
    selected_by_default INTEGER NOT NULL DEFAULT 1,
    active SMALLINT NOT NULL DEFAULT 1
);

-- Table: tblpinned_projects
CREATE TABLE IF NOT EXISTS tblpinned_projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    project_id INTEGER NOT NULL,
    staff_id INTEGER NOT NULL
);

-- Table: tblprojectdiscussioncomments
CREATE TABLE IF NOT EXISTS tblprojectdiscussioncomments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    discussion_id INTEGER NOT NULL,
    discussion_type VARCHAR(10) NOT NULL,
    parent INTEGER,
    created TIMESTAMP NOT NULL,
    modified TIMESTAMP,
    content TEXT NOT NULL,
    staff_id INTEGER NOT NULL,
    contact_id INTEGER DEFAULT 0,
    fullname VARCHAR(191),
    file_name VARCHAR(191),
    file_mime_type VARCHAR(70)
);

-- Table: tblprojectdiscussions
CREATE TABLE IF NOT EXISTS tblprojectdiscussions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    project_id INTEGER NOT NULL,
    subject VARCHAR(191) NOT NULL,
    description TEXT NOT NULL,
    show_to_customer SMALLINT NOT NULL DEFAULT 0,
    datecreated TIMESTAMP NOT NULL,
    last_activity TIMESTAMP,
    staff_id INTEGER NOT NULL DEFAULT 0,
    contact_id INTEGER NOT NULL DEFAULT 0
);

-- Table: tblprojects
CREATE TABLE IF NOT EXISTS tblprojects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(191) NOT NULL,
    description TEXT,
    status INTEGER NOT NULL DEFAULT 0,
    clientid INTEGER NOT NULL,
    billing_type INTEGER NOT NULL,
    start_date DATE NOT NULL,
    deadline DATE,
    project_created DATE NOT NULL,
    date_finished TIMESTAMP,
    progress INTEGER DEFAULT 0,
    progress_from_tasks INTEGER NOT NULL DEFAULT 1,
    project_cost NUMERIC(15,2),
    project_rate_per_hour NUMERIC(15,2),
    estimated_hours NUMERIC(15,2),
    addedfrom INTEGER NOT NULL,
    contact_notification INTEGER DEFAULT 1,
    notify_contacts TEXT
);

-- Table: tblproject_activity
CREATE TABLE IF NOT EXISTS tblproject_activity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    project_id INTEGER NOT NULL,
    staff_id INTEGER NOT NULL DEFAULT 0,
    contact_id INTEGER NOT NULL DEFAULT 0,
    fullname VARCHAR(100),
    visible_to_customer INTEGER NOT NULL DEFAULT 0,
    description_key VARCHAR(191) NOT NULL,
    additional_data TEXT,
    dateadded TIMESTAMP NOT NULL
);

-- Table: tblproject_files
CREATE TABLE IF NOT EXISTS tblproject_files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    file_name VARCHAR(191) NOT NULL,
    original_file_name TEXT,
    subject VARCHAR(191),
    description TEXT,
    filetype VARCHAR(50),
    dateadded TIMESTAMP NOT NULL,
    last_activity TIMESTAMP,
    project_id INTEGER NOT NULL,
    visible_to_customer SMALLINT DEFAULT 0,
    staffid INTEGER NOT NULL,
    contact_id INTEGER NOT NULL DEFAULT 0,
    external VARCHAR(40),
    external_link TEXT,
    thumbnail_link TEXT
);

-- Table: tblproject_members
CREATE TABLE IF NOT EXISTS tblproject_members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    project_id INTEGER NOT NULL,
    staff_id INTEGER NOT NULL
);

-- Table: tblproject_notes
CREATE TABLE IF NOT EXISTS tblproject_notes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    project_id INTEGER NOT NULL,
    title VARCHAR(255),
    content TEXT NOT NULL,
    staff_id INTEGER NOT NULL,
    dateadded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Table: tblproject_settings
CREATE TABLE IF NOT EXISTS tblproject_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    project_id INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    value TEXT
);

-- Table: tblproposals
CREATE TABLE IF NOT EXISTS tblproposals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    subject VARCHAR(191),
    content TEXT,
    addedfrom INTEGER NOT NULL,
    datecreated TIMESTAMP NOT NULL,
    total NUMERIC(15,2),
    subtotal NUMERIC(15,2) NOT NULL,
    total_tax NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    adjustment NUMERIC(15,2),
    discount_percent NUMERIC(15,2) NOT NULL,
    discount_total NUMERIC(15,2) NOT NULL,
    discount_type VARCHAR(30),
    show_quantity_as INTEGER NOT NULL DEFAULT 1,
    currency INTEGER NOT NULL,
    open_till DATE,
    date DATE NOT NULL,
    rel_id INTEGER,
    rel_type VARCHAR(40),
    assigned INTEGER,
    hash VARCHAR(32) NOT NULL,
    proposal_to VARCHAR(191),
    project_id INTEGER,
    country INTEGER NOT NULL DEFAULT 0,
    zip VARCHAR(50),
    state VARCHAR(100),
    city VARCHAR(100),
    address VARCHAR(200),
    email VARCHAR(150),
    phone VARCHAR(50),
    allow_comments SMALLINT NOT NULL DEFAULT 1,
    status INTEGER NOT NULL,
    estimate_id INTEGER,
    invoice_id INTEGER,
    date_converted TIMESTAMP,
    pipeline_order INTEGER DEFAULT 1,
    is_expiry_notified INTEGER NOT NULL DEFAULT 0,
    acceptance_firstname VARCHAR(50),
    acceptance_lastname VARCHAR(50),
    acceptance_email VARCHAR(100),
    acceptance_date TIMESTAMP,
    acceptance_ip VARCHAR(40),
    signature VARCHAR(40),
    short_link VARCHAR(100)
);

-- Table: tblproposal_comments
CREATE TABLE IF NOT EXISTS tblproposal_comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    content TEXT,
    proposalid INTEGER NOT NULL,
    staffid INTEGER NOT NULL,
    dateadded TIMESTAMP NOT NULL
);

-- Table: tblrelated_items
CREATE TABLE IF NOT EXISTS tblrelated_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    rel_id INTEGER NOT NULL,
    rel_type VARCHAR(30) NOT NULL,
    item_id INTEGER NOT NULL
);

-- Table: tblreminders
CREATE TABLE IF NOT EXISTS tblreminders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    description TEXT,
    date TIMESTAMP NOT NULL,
    isnotified INTEGER NOT NULL DEFAULT 0,
    rel_id INTEGER NOT NULL,
    staff INTEGER NOT NULL,
    rel_type VARCHAR(40) NOT NULL,
    notify_by_email INTEGER NOT NULL DEFAULT 1,
    creator INTEGER NOT NULL
);

-- Table: tblroles
CREATE TABLE IF NOT EXISTS tblroles (
    roleid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    permissions TEXT
);

-- Table: tblsales_activity
CREATE TABLE IF NOT EXISTS tblsales_activity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    rel_type VARCHAR(20),
    rel_id INTEGER NOT NULL,
    description TEXT NOT NULL,
    additional_data TEXT,
    staffid VARCHAR(11),
    full_name VARCHAR(100),
    date TIMESTAMP NOT NULL
);

-- Table: tblscheduled_emails
CREATE TABLE IF NOT EXISTS tblscheduled_emails (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    rel_id INTEGER NOT NULL,
    rel_type VARCHAR(15) NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    contacts VARCHAR(197) NOT NULL,
    cc TEXT,
    attach_pdf SMALLINT NOT NULL DEFAULT 1,
    template VARCHAR(197) NOT NULL
);

-- Table: tblservices
CREATE TABLE IF NOT EXISTS tblservices (
    serviceid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL
);

-- Table: tblsessions
CREATE TABLE IF NOT EXISTS tblsessions (
    id VARCHAR(128) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    timestamp INTEGER NOT NULL DEFAULT 0,
    data VARCHAR NOT NULL
);

-- Table: tblshared_customer_files
CREATE TABLE IF NOT EXISTS tblshared_customer_files (
    file_id INTEGER NOT NULL,
    contact_id INTEGER NOT NULL
);

-- Table: tblspam_filters
CREATE TABLE IF NOT EXISTS tblspam_filters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(40) NOT NULL,
    rel_type VARCHAR(10) NOT NULL,
    value TEXT NOT NULL
);

-- Table: tblstaff
CREATE TABLE IF NOT EXISTS tblstaff (
    staffid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(100) NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    facebook TEXT,
    linkedin TEXT,
    phonenumber VARCHAR(30),
    skype VARCHAR(50),
    password VARCHAR(250) NOT NULL,
    datecreated TIMESTAMP NOT NULL,
    profile_image VARCHAR(191),
    last_ip VARCHAR(40),
    last_login TIMESTAMP,
    last_activity TIMESTAMP,
    last_password_change TIMESTAMP,
    new_pass_key VARCHAR(32),
    new_pass_key_requested TIMESTAMP,
    admin INTEGER NOT NULL DEFAULT 0,
    role INTEGER,
    active INTEGER NOT NULL DEFAULT 1,
    default_language VARCHAR(40),
    direction VARCHAR(3),
    media_path_slug VARCHAR(191),
    is_not_staff INTEGER NOT NULL DEFAULT 0,
    hourly_rate NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    two_factor_auth_enabled SMALLINT DEFAULT 0,
    two_factor_auth_code VARCHAR(100),
    two_factor_auth_code_requested TIMESTAMP,
    email_signature TEXT,
    google_auth_secret TEXT
);

-- Table: tblstaff_departments
CREATE TABLE IF NOT EXISTS tblstaff_departments (
    staffdepartmentid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    staffid INTEGER NOT NULL,
    departmentid INTEGER NOT NULL
);

-- Table: tblstaff_permissions
CREATE TABLE IF NOT EXISTS tblstaff_permissions (
    staff_id INTEGER NOT NULL,
    feature VARCHAR(40) NOT NULL,
    capability VARCHAR(100) NOT NULL
);

-- Table: tblsubscriptions
CREATE TABLE IF NOT EXISTS tblsubscriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(191) NOT NULL,
    description TEXT,
    description_in_item SMALLINT NOT NULL DEFAULT 0,
    clientid INTEGER NOT NULL,
    date DATE,
    terms TEXT,
    currency INTEGER NOT NULL,
    tax_id INTEGER NOT NULL DEFAULT 0,
    stripe_tax_id VARCHAR(50),
    tax_id_2 INTEGER NOT NULL DEFAULT 0,
    stripe_tax_id_2 VARCHAR(50),
    stripe_plan_id TEXT,
    stripe_subscription_id TEXT NOT NULL,
    next_billing_cycle BIGINT,
    ends_at BIGINT,
    status VARCHAR(50),
    quantity INTEGER NOT NULL DEFAULT 1,
    project_id INTEGER NOT NULL DEFAULT 0,
    hash VARCHAR(32) NOT NULL,
    created TIMESTAMP NOT NULL,
    created_from INTEGER NOT NULL,
    date_subscribed TIMESTAMP,
    in_test_environment INTEGER,
    last_sent_at TIMESTAMP
);

-- Table: tbltaggables
CREATE TABLE IF NOT EXISTS tbltaggables (
    rel_id INTEGER NOT NULL,
    rel_type VARCHAR(20) NOT NULL,
    tag_id INTEGER NOT NULL,
    tag_order INTEGER NOT NULL DEFAULT 0
);

-- Table: tbltags
CREATE TABLE IF NOT EXISTS tbltags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL
);

-- Table: tbltasks
CREATE TABLE IF NOT EXISTS tbltasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    description TEXT,
    priority INTEGER,
    dateadded TIMESTAMP NOT NULL,
    startdate DATE NOT NULL,
    duedate DATE,
    datefinished TIMESTAMP,
    addedfrom INTEGER NOT NULL,
    is_added_from_contact SMALLINT NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 0,
    recurring_type VARCHAR(10),
    repeat_every INTEGER,
    recurring INTEGER NOT NULL DEFAULT 0,
    is_recurring_from INTEGER,
    cycles INTEGER NOT NULL DEFAULT 0,
    total_cycles INTEGER NOT NULL DEFAULT 0,
    custom_recurring SMALLINT NOT NULL DEFAULT 0,
    last_recurring_date DATE,
    rel_id INTEGER,
    rel_type VARCHAR(30),
    is_public SMALLINT NOT NULL DEFAULT 0,
    billable SMALLINT NOT NULL DEFAULT 0,
    billed SMALLINT NOT NULL DEFAULT 0,
    invoice_id INTEGER NOT NULL DEFAULT 0,
    hourly_rate NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    milestone INTEGER DEFAULT 0,
    kanban_order INTEGER DEFAULT 1,
    milestone_order INTEGER NOT NULL DEFAULT 0,
    visible_to_client SMALLINT NOT NULL DEFAULT 0,
    deadline_notified INTEGER NOT NULL DEFAULT 0
);

-- Table: tbltaskstimers
CREATE TABLE IF NOT EXISTS tbltaskstimers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    task_id INTEGER NOT NULL,
    start_time VARCHAR(64) NOT NULL,
    end_time VARCHAR(64),
    staff_id INTEGER NOT NULL,
    hourly_rate NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    note TEXT
);

-- Table: tbltasks_checklist_templates
CREATE TABLE IF NOT EXISTS tbltasks_checklist_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    description TEXT
);

-- Table: tbltask_assigned
CREATE TABLE IF NOT EXISTS tbltask_assigned (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    staffid INTEGER NOT NULL,
    taskid INTEGER NOT NULL,
    assigned_from INTEGER NOT NULL DEFAULT 0,
    is_assigned_from_contact SMALLINT NOT NULL DEFAULT 0
);

-- Table: tbltask_checklist_items
CREATE TABLE IF NOT EXISTS tbltask_checklist_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    taskid INTEGER NOT NULL,
    description TEXT NOT NULL,
    finished INTEGER NOT NULL DEFAULT 0,
    dateadded TIMESTAMP NOT NULL,
    addedfrom INTEGER NOT NULL,
    finished_from INTEGER DEFAULT 0,
    list_order INTEGER NOT NULL DEFAULT 0,
    assigned INTEGER
);

-- Table: tbltask_comments
CREATE TABLE IF NOT EXISTS tbltask_comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    taskid INTEGER NOT NULL,
    staffid INTEGER NOT NULL,
    contact_id INTEGER NOT NULL DEFAULT 0,
    file_id INTEGER NOT NULL DEFAULT 0,
    dateadded TIMESTAMP NOT NULL
);

-- Table: tbltask_followers
CREATE TABLE IF NOT EXISTS tbltask_followers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    staffid INTEGER NOT NULL,
    taskid INTEGER NOT NULL
);

-- Table: tbltaxes
CREATE TABLE IF NOT EXISTS tbltaxes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    taxrate NUMERIC(15,2) NOT NULL
);

-- Table: tbltemplates
CREATE TABLE IF NOT EXISTS tbltemplates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(100) NOT NULL,
    addedfrom INTEGER NOT NULL,
    content TEXT,
    content_type VARCHAR(20) NOT NULL DEFAULT 'html'
);

-- Table: tbltickets
CREATE TABLE IF NOT EXISTS tbltickets (
    ticketid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    adminreplying INTEGER NOT NULL DEFAULT 0,
    userid INTEGER NOT NULL,
    contactid INTEGER NOT NULL DEFAULT 0,
    merged_ticket_id INTEGER,
    email TEXT,
    name TEXT,
    department INTEGER NOT NULL,
    priority INTEGER NOT NULL,
    status INTEGER NOT NULL,
    service INTEGER,
    ticketkey VARCHAR(32) NOT NULL,
    subject VARCHAR(191) NOT NULL,
    message TEXT,
    admin INTEGER,
    date TIMESTAMP NOT NULL,
    project_id INTEGER NOT NULL DEFAULT 0,
    lastreply TIMESTAMP,
    clientread INTEGER NOT NULL DEFAULT 0,
    adminread INTEGER NOT NULL DEFAULT 0,
    assigned INTEGER NOT NULL DEFAULT 0,
    staff_id_replying INTEGER,
    cc VARCHAR(191)
);

-- Table: tbltickets_pipe_log
CREATE TABLE IF NOT EXISTS tbltickets_pipe_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    date TIMESTAMP NOT NULL,
    email_to VARCHAR(100) NOT NULL,
    name VARCHAR(191) NOT NULL,
    subject VARCHAR(191) NOT NULL,
    message TEXT NOT NULL,
    email VARCHAR(100) NOT NULL,
    status VARCHAR(100) NOT NULL
);

-- Table: tbltickets_predefined_replies
CREATE TABLE IF NOT EXISTS tbltickets_predefined_replies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(191) NOT NULL,
    message TEXT NOT NULL
);

-- Table: tbltickets_priorities
CREATE TABLE IF NOT EXISTS tbltickets_priorities (
    priorityid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL
);

-- Table: tbltickets_status
CREATE TABLE IF NOT EXISTS tbltickets_status (
    ticketstatusid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    isdefault INTEGER NOT NULL DEFAULT 0,
    statuscolor VARCHAR(7),
    statusorder INTEGER
);

-- Table: tblticket_attachments
CREATE TABLE IF NOT EXISTS tblticket_attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ticketid INTEGER NOT NULL,
    replyid INTEGER,
    file_name VARCHAR(191) NOT NULL,
    filetype VARCHAR(50),
    dateadded TIMESTAMP NOT NULL
);

-- Table: tblticket_replies
CREATE TABLE IF NOT EXISTS tblticket_replies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ticketid INTEGER NOT NULL,
    userid INTEGER,
    contactid INTEGER NOT NULL DEFAULT 0,
    name TEXT,
    email TEXT,
    date TIMESTAMP NOT NULL,
    message TEXT,
    attachment INTEGER,
    admin INTEGER
);

-- Table: tbltodos
CREATE TABLE IF NOT EXISTS tbltodos (
    todoid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    description TEXT NOT NULL,
    staffid INTEGER NOT NULL,
    dateadded TIMESTAMP NOT NULL,
    finished SMALLINT NOT NULL,
    datefinished TIMESTAMP,
    item_order INTEGER
);

-- Table: tbltracked_mails
CREATE TABLE IF NOT EXISTS tbltracked_mails (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    uid VARCHAR(32) NOT NULL,
    rel_id INTEGER NOT NULL,
    rel_type VARCHAR(40) NOT NULL,
    date TIMESTAMP NOT NULL,
    email VARCHAR(100) NOT NULL,
    opened SMALLINT NOT NULL DEFAULT 0,
    date_opened TIMESTAMP,
    subject TEXT
);

-- Table: tbltwocheckout_log
CREATE TABLE IF NOT EXISTS tbltwocheckout_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    reference VARCHAR(64) NOT NULL,
    invoice_id INTEGER NOT NULL,
    amount VARCHAR(25) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    attempt_reference VARCHAR(100)
);

-- Table: tbluser_auto_login
CREATE TABLE IF NOT EXISTS tbluser_auto_login (
    key_id VARCHAR(64) NOT NULL,
    user_id INTEGER NOT NULL,
    user_agent VARCHAR(150) NOT NULL,
    last_ip VARCHAR(40) NOT NULL,
    last_login VARCHAR NOT NULL DEFAULT CURRENT_TIMESTAMP,
    staff INTEGER NOT NULL
);

-- Table: tbluser_meta
CREATE TABLE IF NOT EXISTS tbluser_meta (
    umeta_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    staff_id BIGINT NOT NULL DEFAULT 0,
    client_id BIGINT NOT NULL DEFAULT 0,
    contact_id BIGINT NOT NULL DEFAULT 0,
    meta_key VARCHAR(191),
    meta_value TEXT
);

-- Table: tblvault
CREATE TABLE IF NOT EXISTS tblvault (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    customer_id INTEGER NOT NULL,
    server_address VARCHAR(191) NOT NULL,
    port INTEGER,
    username VARCHAR(191) NOT NULL,
    password TEXT NOT NULL,
    description TEXT,
    creator INTEGER NOT NULL,
    creator_name VARCHAR(100),
    visibility SMALLINT NOT NULL DEFAULT 1,
    share_in_projects SMALLINT NOT NULL DEFAULT 0,
    last_updated TIMESTAMP,
    last_updated_from VARCHAR(100),
    date_created TIMESTAMP NOT NULL
);

-- Table: tblviews_tracking
CREATE TABLE IF NOT EXISTS tblviews_tracking (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    rel_id INTEGER NOT NULL,
    rel_type VARCHAR(40) NOT NULL,
    date TIMESTAMP NOT NULL,
    view_ip VARCHAR(40) NOT NULL
);

-- Table: tblweb_to_lead
CREATE TABLE IF NOT EXISTS tblweb_to_lead (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    form_key VARCHAR(32) NOT NULL,
    lead_source INTEGER NOT NULL,
    lead_status INTEGER NOT NULL,
    notify_lead_imported INTEGER NOT NULL DEFAULT 1,
    notify_type VARCHAR(20),
    notify_ids TEXT,
    responsible INTEGER NOT NULL DEFAULT 0,
    name VARCHAR(191) NOT NULL,
    form_data TEXT,
    recaptcha INTEGER NOT NULL DEFAULT 0,
    submit_btn_name VARCHAR(40),
    submit_btn_text_color VARCHAR(10) DEFAULT '#ffffff',
    submit_btn_bg_color VARCHAR(10) DEFAULT '#84c529',
    success_submit_msg TEXT,
    submit_action INTEGER DEFAULT 0,
    lead_name_prefix VARCHAR(255),
    submit_redirect_url TEXT,
    language VARCHAR(40),
    allow_duplicate INTEGER NOT NULL DEFAULT 1,
    mark_public INTEGER NOT NULL DEFAULT 0,
    track_duplicate_field VARCHAR(20),
    track_duplicate_field_and VARCHAR(20),
    create_task_on_duplicate INTEGER NOT NULL DEFAULT 0,
    dateadded TIMESTAMP NOT NULL
);

-- Table: __pfx__woocommerce_stores
CREATE TABLE IF NOT EXISTS __pfx__woocommerce_stores (

);

